- name: Web servers setup 
  hosts: [all]
  become: true
  roles: 
    - docker
- name: Install interpreter
  hosts: all
  become: yes
  tasks:
    - name: Install Python pip
      apt:
        name: python3-pip
        state: present

    - name: Install Docker SDK for Python
      pip:
        name: docker
        state: present
- name: Create a Docker network and volumes
  hosts: all 
  become: yes
  tasks: 
    - name: Create a Docker network
      docker_network: 
        name: spring-mysql-net
        state: present
    - name: Create a volume for storing db
      community.docker.docker_volume:
        name: db-data
- name: Run containers 
  hosts: [all]
  become: true
  roles: 
    - db
    - api
    - web